name: First workflow
on: [push, pull_request]

jobs:
  first-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Display path and file rep
        run: |
          pwd
          ls -a
  second-workflows:
    runs-on: ubuntu-latest
    needs: first-workflows
    steps:
      - name: Upload prog
        uses: actions/checkout@v6

      - name: Check dir
        run: |
          ls -a
          echo "completed"
