name: First workflow
on: [push]

jobs:
  first-run-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display text
        run: echo "run!"
      - name: Commands
        run: |
          python -version
